### ISSUE TITLE
[infra] stop -> start 시 docker 가 뜨지 않는 이슈

### ISSUE THREAD

**Issue by HAN-SEOHYUN** [IDWWT/hello-utils#69]
```
./scripts/stop.sh 
./scripts/start.sh 
```
![image](https://github.com/IDWWT/hello-utils/assets/105329813/c01a4cf3-2f4f-45a3-b7e6-4187d21ad0de)

start 시 컨테이너가 모두 뜨는 것이 보장되지 않음.
어쩔때는 떴다가 어쩔때는 안떴다가 함. 😭

**Comment by ro-ssang** [comment]
* 헬스 체크 옵션을 다음과 같이 수정함

```
interval: 5s
timeout: 3s
start_period: 0s
retries: 6
```
